project_name: example1

before:
  hooks:
    - rm -rf dist
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
      - -X example1/version.Version=v{{.Version}}

snapshot:
  name_template: "{{ incminor .Version }}-dev"

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
  algorithm: sha256

brews:
  - name: example1
    tap:
      owner: ondrejsikademo
      name: homebrew-tap
    skip_upload: auto
    homepage: https://github.com/golang-training-examples/example1
    url_template: "https://github.com/golang-training-examples/example1/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    folder: Formula
    caveats: "How to use this binary: https://github.com/golang-training-examples/example1"
    description: "Example for Golang Training"
    install: |
      bin.install "example1"
    test: |
      system "#{bin}/example1"
